### ISSUE TITLE
Реализовать базовый сбор статистики 

### ISSUE THREAD

**Issue by vetand** [vetand/code-statistics#3]
Необходимо реализовать класс `CollectCommentLines` для сбора статистики по файлу + придумать что-нибудь похожее по образцу.

- [x] Стереть заглушку в классе `CollectCommentLines` 
- [x] Реализовать метод `.collect(String fileName)` - см. юнит-тест
- [x] Пройти юнит-тест `testCollectCommentLines`
- [x] Реализовать класс по образцу `CollectCommentLines`
- [x] Написать к нему юнит-тест, ну и конечно пройти его

**Comment by matveevk** [comment]
Бывают ещё multi-line комменты (`/*...*/`), их хочу отдельно от однострочных посчитать. Я обновлю юнит-тест под новую логику, ок? @vetand

**Comment by vetand** [comment]
> Бывают ещё multi-line комменты (`/*...*/`), их хочу отдельно от однострочных посчитать. Я обновлю юнит-тест под новую логику, ок? @vetand

Да, давай, только сделай так, чтобы все остальные юнит-тесты проходили

**Comment by vetand** [comment]
Done
