### ISSUE TITLE
Реализовать обход папки проекта

### ISSUE THREAD

**Issue by vetand** [vetand/code-statistics#4]
Необходимо реализовать рекурсивный обход папки проекта, отобрать необходимые C-like файлы и вывести структуру проекта.

- [x] Стереть заглушки в классе `ProjectTree`
- [x] Реализовать рекурсивный обход дерева проекта с отбором только нужных нам файлов (вызываем из конструктора) - см. юнит тест
- [x] Выдать все эти файлы в методе `.getValidFiles()`
- [x] Вывести дерево проекта в методе `.getProjectTreeReport()`. Возможно, для этого есть какая-то стандартная либа
- [x] Пройти юнит-тесты `testProjectTreeFilesDIR` и `testProjectTreeStructure`.

**Comment by timurvankov** [comment]
```.getProjectTreeReport()``` я бы поменял это название просто на ```.getProjectTree()```

**Comment by vetand** [comment]
> `.getProjectTreeReport()` я бы поменял это название просто на `.getProjectTree()`

Ок, без проблем. Только кинь чуть пораньше дедлайна, т. к. его уже используют

**Comment by timurvankov** [comment]
> Ок, без проблем. Только кинь чуть пораньше дедлайна, т. к. его уже используют

всм используют?

**Comment by vetand** [comment]
> > Ок, без проблем. Только кинь чуть пораньше дедлайна, т. к. его уже используют
> 
> всм используют?

У людей параллельные таски с этим интерфейсом. Нужно либо сразу поменять, либо после первой итерации, когда всё мержить будем.

**Comment by timurvankov** [comment]
Когда дедлайн? @vetand
